#!/usr/bin/env python
"""
Regenerate the OPENAI_MODELS / ANTHROPIC_MODELS fast-path lists in
aider/models.py from litellm's bundled model_cost data.

Why this exists (see ARCHITECTURE_REVIEW.md / BUILD_PLAN.md Phase 1):
`Model.fast_validate_environment()` uses these two lists purely as a
fast path to resolve which API-key env var a model needs, specifically
to avoid forcing litellm's ~1.5s import for the common case. That means
the lists can't simply be computed at runtime from litellm without
defeating their own purpose -- so instead we regenerate them here, as a
maintenance script, and commit the result. This replaces "a human
manually retypes a Python list of model names on every release" with
"run one script and commit the diff", removing the drift/staleness
problem without touching the runtime performance characteristics.

Usage:
    python scripts/update_model_lists.py [--check]

    --check   Exit non-zero if regenerating would change models.py
              (for CI use), instead of writing the file.

This intentionally does NOT run automatically on every aider launch --
it's meant to be run periodically (e.g. a scheduled CI job, or by hand
before a release) and the diff reviewed like any other change.
"""

import argparse
import re
import sys
from pathlib import Path

MODELS_PY = Path(__file__).resolve().parent.parent / "aider" / "models.py"

START_MARKER = "# --- BEGIN GENERATED FAST-PATH MODEL LISTS ---"
END_MARKER = "# --- END GENERATED FAST-PATH MODEL LISTS ---"


def get_provider_models(provider: str) -> list[str]:
    from aider.llm import litellm

    litellm._load_litellm()
    model_cost = litellm._lazy_module.model_cost

    names = [
        name
        for name, info in model_cost.items()
        if info.get("litellm_provider") == provider and "/" not in name
    ]
    return sorted(set(names))


def render_block(openai_models: list[str], anthropic_models: list[str]) -> str:
    def render_list(var_name: str, models: list[str]) -> str:
        lines = "\n".join(models)
        return (
            f'{var_name} = """\n{lines}\n"""\n\n'
            f"{var_name} = [ln.strip() for ln in {var_name}.splitlines() if ln.strip()]"
        )

    return (
        f"{START_MARKER}\n"
        "# Generated by scripts/update_model_lists.py from litellm's bundled\n"
        "# model_cost data. Do not hand-edit -- rerun the script instead.\n"
        f"{render_list('OPENAI_MODELS', openai_models)}\n\n"
        f"{render_list('ANTHROPIC_MODELS', anthropic_models)}\n"
        f"{END_MARKER}"
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if models.py would change, instead of writing it.",
    )
    args = parser.parse_args()

    openai_models = get_provider_models("openai")
    anthropic_models = get_provider_models("anthropic")
    new_block = render_block(openai_models, anthropic_models)

    text = MODELS_PY.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL)
    if not pattern.search(text):
        print(f"ERROR: markers not found in {MODELS_PY}", file=sys.stderr)
        sys.exit(2)

    new_text = pattern.sub(new_block.replace("\\", "\\\\"), text, count=1)

    if new_text == text:
        print("No changes.")
        return

    if args.check:
        print("models.py is stale -- run scripts/update_model_lists.py to refresh.")
        sys.exit(1)

    MODELS_PY.write_text(new_text, encoding="utf-8")
    print(
        f"Updated {MODELS_PY}: {len(openai_models)} OpenAI models, "
        f"{len(anthropic_models)} Anthropic models."
    )


if __name__ == "__main__":
    main()
